kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: python:3.7.4-alpine3.10
  commands:
    - apk add --no-cache build-base libxml2-dev libxslt-dev
    - pip install pipenv
    - cd devpost-api
    - pipenv sync
    - pipenv run python test.py
- name: docker  
  image: plugins/docker
  settings:
    repo: virb3/devpost-api
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD