kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine:3.10
  commands:
    - apk add --no-cache python3 py3-lxml
    - pip3 install pipenv
    - cd devpost-api
    # workaround https://github.com/pypa/pipenv/issues/3718
    - pipenv install --system --deploy --ignore-pipfile
    - python3 test.py
- name: docker
  image: plugins/docker
  settings:
    repo: virb3/devpost-api
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD