language: minimal

env:
  global:
    - REPO_NAME=virb3/devpost-api
    - DOCKER_CLI_EXPERIMENTAL=enabled

stages:
  - name: test
  - name: deploy
    if: type != cron

before_script:
  - set -e

jobs:
  include:
    - stage: test
      script:
        - docker build --target test -t $REPO_NAME:test .
        - docker run $REPO_NAME:test

    # https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/getting-started-with-docker-for-arm-on-linux
    - stage: deploy
      before_script:
        # need Docker > 19.03 for buildx
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
      script:
        - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
        - docker buildx create --name mybuilder
        - docker buildx use mybuilder
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 --push -t $REPO_NAME .
